<?php 
require_once '../includes/auth.php';
require_once '../includes/db.php';

use RobThree\Auth\TwoFactorAuth;
use RobThree\Auth\Providers\Qr\QRServerProvider;

$admin = getCurrentAdmin();
if (!$admin) {
    header('Location: login.php');
    exit;
}

// Check if 2FA is already enabled
$db = (new Database())->connect();
$stmt = $db->prepare("SELECT two_factor_enabled FROM admins WHERE id = ?");
$stmt->execute([$admin['id']]);
$adminDetails = $stmt->fetch(PDO::FETCH_ASSOC);

if ($adminDetails['two_factor_enabled']) {
    header('Location: profile.php');
    exit;
}

// Create QR provider instance
$qrProvider = new QRServerProvider();

// Setup 2FA if not already done
if (!isset($_SESSION['admin_2fa_setup_mode'])) {
    $secret = setupAdminTwoFactorAuth($admin['id']);
    $_SESSION['admin_2fa_setup_mode'] = true;
    $_SESSION['admin_2fa_secret'] = $secret;
} else {
    $secret = $_SESSION['admin_2fa_secret'];
}

// Handle form submission
$error = '';
if ($_SERVER['REQUEST_METHOD'] === 'POST' && isset($_POST['verify_code'])) {
    $code = $_POST['code'] ?? '';
    
    if (verifyAdminTwoFactorCode($admin['id'], $code)) {
        // 2FA verified and enabled - redirect to profile
        header('Location: profile.php');
        exit;
    } else {
        $error = 'Invalid verification code. Please try again.';
    }
}

// Generate QR code URL
$tfa = new TwoFactorAuth($qrProvider, 'StepCashier'); 
$qrCodeUrl = $tfa->getQRCodeImageAsDataUri($admin['email'], $secret);

include '../includes/admin_header.php'; 
?>

<div class="bg-white shadow rounded-lg overflow-hidden max-w-2xl mx-auto">
    <div class="px-4 py-5 sm:px-6 border-b border-gray-200">
        <h3 class="text-lg leading-6 font-medium text-gray-900">Enable Two-Factor Authentication</h3>
        <p class="mt-1 text-sm text-gray-500">Add an extra layer of security to your account</p>
    </div>
    
    <div class="px-4 py-5 sm:p-6">
        <div class="space-y-6">
            <div>
                <p class="text-sm text-gray-600 mb-4">To enable two-factor authentication, follow these steps:</p>
                
                <ol class="list-decimal list-inside space-y-2 text-sm text-gray-600">
                    <li>Download an authenticator app like Google Authenticator or Authy on your mobile device</li>
                    <li>Scan the QR code below with your authenticator app</li>
                    <li>Enter the 6-digit code generated by the app to verify</li>
                </ol>
            </div>
            
            <div class="flex flex-col items-center">
                <!-- QR Code -->
                <div class="bg-white p-4 rounded border border-gray-200 mb-4">
                    <img src="<?php echo $qrCodeUrl; ?>" alt="QR Code" class="w-48 h-48">
                </div>
                
                <div class="text-center">
                    <p class="text-sm text-gray-600 mb-2">Or enter this secret key manually:</p>
                    <div class="bg-gray-100 p-3 rounded-md inline-block">
                        <code class="text-sm font-mono"><?php echo chunk_split($secret, 4, ' '); ?></code>
                    </div>
                </div>
            </div>
            
            <!-- Verification Form -->
            <form action="<?php echo htmlspecialchars($_SERVER['PHP_SELF']); ?>" method="POST">
                <?php if ($error): ?>
                    <div class="rounded-md bg-red-50 p-4 mb-4">
                        <div class="flex">
                            <div class="flex-shrink-0">
                                <svg class="h-5 w-5 text-red-400" xmlns="http://www.w3.org/2000/svg" viewBox="0 0 20 20" fill="currentColor">
                                    <path fill-rule="evenodd" d="M10 18a8 8 0 100-16 8 8 0 000 16zM8.707 7.293a1 1 0 00-1.414 1.414L8.586 10l-1.293 1.293a1 1 0 101.414 1.414L10 11.414l1.293 1.293a1 1 0 001.414-1.414L11.414 10l1.293-1.293a1 1 0 00-1.414-1.414L10 8.586 8.707 7.293z" clip-rule="evenodd" />
                                </svg>
                            </div>
                            <div class="ml-3">
                                <h3 class="text-sm font-medium text-red-800"><?php echo $error; ?></h3>
                            </div>
                        </div>
                    </div>
                <?php endif; ?>
                
                <div>
                    <label for="code" class="block text-sm font-medium text-gray-700">Verification Code</label>
                    <div class="mt-1">
                        <input type="text" name="code" id="code" class="shadow-sm focus:ring-primary focus:border-primary block w-full sm:text-sm border-gray-300 rounded-md" placeholder="Enter 6-digit code" maxlength="6" pattern="\d{6}" required>
                    </div>
                    <p class="mt-2 text-sm text-gray-500">Enter the 6-digit code from your authenticator app</p>
                </div>
                
                <div class="mt-6 flex justify-end space-x-3">
                    <a href="profile.php" class="inline-flex justify-center py-2 px-4 border border-gray-300 shadow-sm text-sm font-medium rounded-md text-gray-700 bg-white hover:bg-gray-50 focus:outline-none focus:ring-2 focus:ring-offset-2 focus:ring-primary">
                        Cancel
                    </a>
                    <button type="submit" name="verify_code" class="inline-flex justify-center py-2 px-4 border border-transparent shadow-sm text-sm font-medium rounded-md text-white bg-primary hover:bg-primaryDark focus:outline-none focus:ring-2 focus:ring-offset-2 focus:ring-primary">
                        Verify & Enable
                    </button>
                </div>
            </form>
        </div>
    </div>
</div>

<?php include '../includes/admin_footer.php'; ?>